34 facebook connect
MerwaneHAMADI/crowdfunding pull request #18
Opened 2019-11-18 14:48 UTC by MerwaneHAMADI

https://trello.com/c/0PjqdIxD/34-facebook-connect

2019-11-20 08:41 UTC, Kernael requested changes

2019-11-20 08:41 UTC, Kernael commented on app/controllers/users/omniauth_callbacks_controller.rb
> +      sign_in_and_redirect User.find_by_email(@user.email), event: :authentication
Tu fais des requêtes ici pour trouver l'utilisateur alors que tu pourrais en faire une seule pour à la fois la condition et le sign_in

2019-11-20 08:41 UTC, Kernael commented on config/initializers/devise.rb
> +  config.omniauth :facebook, ENV['FACEBOOK_APP_ID'], ENV['FACEBOOK_APP_SECRET'], callback_url: "http://localhost:3000/users/auth/facebook/callback", scope: "email, user_birthday", info_fields: 'first
le `callback_url` ne fonctionnera qu'en local du coup

2019-11-20 16:16 UTC, MerwaneHAMADI commented on app/controllers/users/omniauth_callbacks_controller.rb
> +      sign_in_and_redirect User.find_by_email(@user.email), event: :authentication
oui je vois. Next PR.

2019-11-20 16:23 UTC, MerwaneHAMADI commented on config/initializers/devise.rb
> +  config.omniauth :facebook, ENV['FACEBOOK_APP_ID'], ENV['FACEBOOK_APP_SECRET'], callback_url: "http://localhost:3000/users/auth/facebook/callback", scope: "email, user_birthday", info_fields: 'first
Oui je pense que je devrais appeler Rails.application.routes.default_url_options[:host]

Next PR

2019-11-21 09:10 UTC, Kernael approved these changes

2019-11-21 10:03 UTC, merged