19-seed
MerwaneHAMADI/crowdfunding pull request #4
Opened 2019-11-07 08:57 UTC by MerwaneHAMADI

https://trello.com/c/Eta5H1Fh/19-seed

Corrections branches precedentes

2019-11-07 10:42 UTC, Kernael requested changes

2019-11-07 10:42 UTC, Kernael commented on app/transactions/create_user.rb
>      @user = User.last
Pourquoi ne pas simplement utiliser @user ici au lieu de le redéfinir ? Surtout que rien ne te garanti que User.last sera l'utilisateur concerné

2019-11-07 10:42 UTC, Kernael commented on db/seeds.rb
> +  end
deux petits soucis ici :

- ta condition est inversée, tu ne dois créer l'utilisateur que si il n'existe pas, pas l'inverse. tu peux utiliser la méthode `find_or_create_by!` pour ça

- tu répètes la condition `Rails.env.development?` alors que le premier `if` se charge déjà de ça

2019-11-07 17:07 UTC, MerwaneHAMADI commented on app/transactions/create_user.rb
>      @user = User.last
J'etais pas sur d'avoir accès à cet @user, mais en fait si, c'est dans create_user.rb.
Je corrige dans la prochaine PR.

2019-11-07 17:10 UTC, MerwaneHAMADI commented on db/seeds.rb
> +  end
Exact, je modifie dans la prochaine PR

2019-11-08 15:45 UTC, MerwaneHAMADI commented
Normalement les PR qui ont suivi ont réglé le probleme.

2019-11-08 15:55 UTC, Kernael approved these changes

2019-11-08 16:06 UTC, merged