18 crudadmin
MerwaneHAMADI/crowdfunding pull request #5
Opened 2019-11-07 10:38 UTC by MerwaneHAMADI

https://trello.com/c/y8NGEuqr/18-back-office-crud-utilisateur-admin

2019-11-07 16:54 UTC, Kernael requested changes

2019-11-07 16:54 UTC, Kernael commented on db/seeds.rb
> +    User.create!(first_name: "first_name1", last_name:"last_name2", birth_date:"12-01-1993",email: 'user1@capsens.eu', password: 'password1', password_confirmation: 'password1') if Rails.env.developm
tu peux utiliser `find_or_create_by!`

2019-11-07 17:11 UTC, MerwaneHAMADI commented on db/seeds.rb
> +    User.create!(first_name: "first_name1", last_name:"last_name2", birth_date:"12-01-1993",email: 'user1@capsens.eu', password: 'password1', password_confirmation: 'password1') if Rails.env.developm
Ok je corrige a la prochaine PR

2019-11-07 17:16 UTC, MerwaneHAMADI commented on db/seeds.rb
> +    User.create!(first_name: "first_name1", last_name:"last_name2", birth_date:"12-01-1993",email: 'user1@capsens.eu', password: 'password1', password_confirmation: 'password1') if Rails.env.developm
si ca te va je vais plutot destroy_all tout avant. C'est l'option 'soft' que vous avez dans fundhero (j'ai regardé sur github).
T'en penses quoi ?

2019-11-07 17:20 UTC, Kernael requested changes

2019-11-07 17:20 UTC, Kernael commented on db/seeds.rb
> +    User.create!(first_name: "first_name1", last_name:"last_name2", birth_date:"12-01-1993",email: 'user1@capsens.eu', password: 'password1', password_confirmation: 'password1') if Rails.env.developm
Je n'aime pas trop parce-que le fichier de seeds est vraiment fait pour créer de la donnée, donc c'est pas très cohérent. Pour l'admin tu peux laisser ça comme ça, mais pour les `User` tu pourrais plutôt les générer aléatoirement avec `Faker` et `FactoryBot` par exemple pour éviter d'avoir besoin de faire `unless User.find_by...` à chaque fois

2019-11-08 14:14 UTC, MerwaneHAMADI commented on db/seeds.rb
> +    User.create!(first_name: "first_name1", last_name:"last_name2", birth_date:"12-01-1993",email: 'user1@capsens.eu', password: 'password1', password_confirmation: 'password1') if Rails.env.developm
Ok, je vais faire une autre version de la seed avec factory bot et en évitant de destroy_all, tu me diras ce que t'en penses. prochaine PR

2019-11-08 16:10 UTC, Kernael approved these changes

2019-11-08 16:12 UTC, merged